export {
  DEFAULT_USER_ID,
  normalizeUserId,
  userRoot,
  packagesDir,
  recordsDir,
  mediaDir,
  packagePath,
  manifestPath,
  recordPath,
  logPath,
  globalLogPath,
  globalSRSPath,
  mediaPath,
  globalRecordPath,
  buildSlug,
  ensureDataDirs,
} from './paths';

export {
  PackageManifestSchema,
  PACKAGE_FORMAT_VERSION,
  VocabularyRecordSchema,
  type PackageManifest,
  type PackageLesson,
  type PackageScript,
  type CFRecord,
  type CFState,
  type CFSRS,
  type AttemptRecord,
  type TransformRecord,
  type RoleplaySessionRecord,
  type RoleplayMessage,
  type TransformEvent,
  type AttemptEvent,
  type RoleplaySessionEvent,
  type RoleplayMessageEvent,
} from './schema';

export {
  writePackage,
  readPackageManifest,
  readPackageAudio,
  readPackageImage,
  listPackages,
  resolveUniqueSlug,
  pruneOrphanMedia,
  deletePackage,
  renamePackageTopic,
  PackageNotFoundError,
  PackageCorruptError,
  type WritePackageInput,
  type WritePackageResult,
} from './package';

export {
  readRecord,
  readGlobalRecord,
  appendAttempt,
  completePuzzle,
  appendTransform,
  upsertRoleplaySession,
  readAllProgress,
  captureVocabulary,
  deleteHistoryEvent,
  deleteRoleplaySession,
  renameRoleplaySession,
  listEventIdsForSlug,
  listTransformEvents,
  listRoleplaySessions,
  removeStateDoc,
  orphanVocabularyForSlug,
  type TransformHistoryEntry,
  type RoleplaySessionEntry,
  type RoleplayMessageEntry,
  RecordCorruptError,
  db,
  providerFor,
  type AttemptInput,
  type RoleplayUpsertInput,
} from './record';

export { migrateFilesToPouch } from './migrate-to-pouch';
